/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description How long a `GET` takes to become possible.
         *
         *     The download path and the UI branch on **this**, not on the provider name. That is
         *     what lets Azure Archive or LTO tape slot in later without special-casing (§6.1).
         * @enum {string}
         */
        LatencyClass: "instant" | "seconds" | "minutes" | "hours" | "days";
        /**
         * @description Lifecycle state of one `object_placements` row.
         *
         *     Mirrors the `object_placements.state` CHECK. In `dam-core` rather than `dam-store`
         *     because both the database layer that loads it and the resolution layer that acts on it
         *     need the same vocabulary — and a second definition is how the two drift.
         *
         *     Only `Present` is readable. The others each mean something different to an operator,
         *     which is why this is not a boolean: `Uploading` will resolve itself, `Missing` needs a
         *     re-replication, `Corrupt` needs a scrub, and `Deleting` is expected to disappear.
         * @enum {string}
         */
        PlacementState: "uploading" | "present" | "transitioning" | "missing" | "corrupt" | "deleting";
        /**
         * @description Content-credential verification outcome. Mirrors the `assets.provenance_state` CHECK.
         *
         *     Four states rather than a boolean because they call for different responses: `None` is a file that
         *     never had a credential, `Invalid` is one whose credential no longer matches its bytes, and
         *     `Untrusted` is an intact credential from a signer outside any trust list. Collapsing them loses
         *     the distinction between "no claim was made" and "a claim was made and broken".
         * @enum {string}
         */
        ProvenanceState: "none" | "valid" | "invalid" | "untrusted";
        /**
         * @description Where a restore has got to, matching `object_placements.restore_state`.
         * @enum {string}
         */
        RestoreState: "none" | "requested" | "ongoing" | "available" | "expired";
        /**
         * @description Retrieval speed for a restore, matching `restore_requests.tier`.
         * @enum {string}
         */
        RestoreTier: "expedited" | "standard" | "bulk";
        /**
         * @description Rights evaluation outcome for an asset. Mirrors the `assets.rights_state` CHECK.
         * @enum {string}
         */
        RightsState: "allowed" | "expiring" | "denied" | "unknown";
        /**
         * @description S3 storage classes, matching `object_placements.storage_class`.
         * @enum {string}
         */
        StorageClass: "STANDARD" | "STANDARD_IA" | "ONEZONE_IA" | "INTELLIGENT_TIERING" | "GLACIER_IR" | "GLACIER" | "DEEP_ARCHIVE";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
