/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A page of assets the caller may see. */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One asset in full. */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The categories an asset is filed in. */
        get: operations["of_asset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Files an asset in a category. */
        put: operations["file"];
        post?: never;
        /** Takes an asset out of a category. */
        delete: operations["unfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edits an asset's metadata. */
        patch: operations["update_metadata"];
        trace?: never;
    };
    "/assets/{asset_id}/metadata-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The type an asset has, and the form that follows from it. */
        get: operations["read_asset_type"];
        /** Sets or clears an asset's metadata type. */
        put: operations["set_asset_type"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a bulk operation and queues its execution. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulk/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Previews a bulk operation without recording anything. */
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulk/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The progress of one operation. */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every category tree. */
        get: operations["list_trees"];
        put?: never;
        /** Creates a category tree. */
        post: operations["create_tree"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{tree_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One tree, with the caller's own counts. */
        get: operations["read_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{tree_id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a category within a tree. */
        post: operations["create_node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{tree_id}/uncategorised": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many of the caller's assets are in no category of this tree. */
        get: operations["uncategorised"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The tenant's field definitions, in display order. */
        get: operations["fields"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every field definition with its usage counts. */
        get: operations["list"];
        put?: never;
        /** Defines a new field. */
        post: operations["define"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/fields/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Sets the complete field order. */
        put: operations["reorder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/fields/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes a field definition, keeping its stored values. */
        delete: operations["remove"];
        options?: never;
        head?: never;
        /** Amends a field. */
        patch: operations["amend"];
        trace?: never;
    };
    "/schema/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every metadata type, in display order. */
        get: operations["list_types"];
        put?: never;
        /** Creates a metadata type. */
        post: operations["define_type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes a metadata type. Assets carrying it fall back rather than being blocked or orphaned. */
        delete: operations["remove_type"];
        options?: never;
        head?: never;
        /** Amends a metadata type. */
        patch: operations["amend_type"];
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranked results for a shorthand query. */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facet counts for the caller's visible library, narrowed by the same query the results were. */
        get: operations["facets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolves a share for viewing. Does not consume a download. */
        post: operations["portal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/{token}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consumes one download and mints the URL for it. */
        post: operations["download"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The tenant's share links, newest first. */
        get: operations["list"];
        put?: never;
        /** Shares an asset. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revokes a share. Takes effect on URLs the share already minted, because the share id is in their
         *     signatures and delivery re-checks it on every request.
         */
        delete: operations["revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description What to change. An omitted member is left alone; `search_alias: null` clears it. */
        AmendRequest: {
            ai_writable?: boolean | null;
            facetable?: boolean | null;
            kind?: string | null;
            label?: string | null;
            multivalued?: boolean | null;
            read_only?: boolean | null;
            required?: boolean | null;
            /**
             * @description Doubly optional: absent leaves the alias alone, `null` removes it. Those are different intents and
             *     a single `Option` cannot express both.
             */
            search_alias?: string | null;
            searchable?: boolean | null;
            /** Format: uuid */
            taxonomy_id?: string | null;
            validation?: unknown;
        };
        /**
         * @description What to change about a type. An omitted member is left alone.
         *
         *     `field_keys` replaces the list wholesale rather than merging: a type's fields are an ordered list, and
         *     "add this one" computed against a client's stale copy would silently drop whatever it had not seen.
         */
        AmendTypeRequest: {
            applies_to?: string[] | null;
            field_keys?: string[] | null;
            is_default?: boolean | null;
            label?: string | null;
        };
        /** @description An amended field, with the consequences of the amendment. */
        AmendedField: components["schemas"]["SchemaField"] & {
            /**
             * Format: int64
             * @description How many live assets would now fail a metadata write for want of a newly-required value.
             */
            assets_now_incomplete: number;
            /** @description Whether the search index is now stale and needs rebuilding. */
            reindex_required: boolean;
        };
        /** @description One asset in full, as the detail panel draws it. */
        AssetDetail: components["schemas"]["AssetSummary"] & {
            color_space?: string | null;
            /** @description BLAKE3 of the original bytes, lowercase hex. What deduplication and integrity both key on. */
            content_hash: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            duration_ms?: number | null;
            enrichment_state: string;
            /** Format: date-time */
            expires_at?: string | null;
            has_alpha?: boolean | null;
            /**
             * @description Blocks tiering *and* deletion. Surfaced because a user who cannot delete an asset deserves to know
             *     why rather than to see a failing button.
             */
            legal_hold: boolean;
            /** Format: int32 */
            page_count?: number | null;
            /**
             * @description A signed internal-preview URL for the `preview-1024` rendition, when one has been rendered.
             *
             *     On the detail endpoint only. A list of sixty of these would mint sixty tokens for images no grid draws —
             *     the grid uses the thumbnail — and a lightbox opens one asset at a time.
             *
             *     `Contain`-fitted rather than cropped, which is what makes it the right image for somebody inspecting an
             *     asset: the thumbnail is a 256px square crop, so enlarging it is a blurry crop of the wrong aspect.
             */
            preview_url?: string | null;
            /** Format: date-time */
            release_at?: string | null;
            status: string;
            /**
             * @description Probed technical facts — EXIF, codec, colour. Read-only, and shaped by the file rather than by the
             *     tenant's schema, so it is not merged into `values`.
             */
            technical: unknown;
            /** Format: date-time */
            updated_at: string;
            /** @description The validated metadata, keyed by field definition key. */
            values: unknown;
            /** Format: int32 */
            version_no: number;
        };
        /**
         * @description One page of results.
         *
         *     `total` is separate from `items.len()` and load-bearing for accessibility: a virtualised grid must
         *     report the real row count in `aria-rowcount`, or a screen reader announces "20 items" for a library
         *     of a hundred thousand.
         */
        AssetPage: {
            items: components["schemas"]["AssetSummary"][];
            /**
             * Format: int64
             * @description Zero-based index of the first item in `items` within the full result set.
             */
            offset: number;
            /**
             * Format: int64
             * @description Total matching assets, not the number returned.
             */
            total: number;
        };
        /**
         * @description One asset, as the grid renders it.
         *
         *     Deliberately small. A 100k-row grid fetches pages of these, so every field here is multiplied by
         *     the page size — and anything a cell does not draw belongs on the detail endpoint instead.
         */
        AssetSummary: {
            /** Format: int64 */
            bytes: number;
            /** @description The name the uploader gave it, preserved verbatim. The stored MIME is sniffed, not this. */
            filename: string;
            /** Format: int32 */
            height?: number | null;
            /** Format: uuid */
            id: string;
            /** @description Sniffed on ingest, never taken from the client (`assets.mime`). */
            mime: string;
            provenance_state: components["schemas"]["ProvenanceState"];
            /**
             * @description Rights evaluation outcome. A *display* input: enforcement happens at the distribution
             *     chokepoint (D12), and this field is what dims a button rather than what protects an asset.
             */
            rights_state: components["schemas"]["RightsState"];
            /**
             * Format: float
             * @description Model confidence in the asset's automatic tags, 0..1. `None` means nothing scored it — which
             *     is not the same as zero, and the UI renders it differently.
             */
            tag_confidence?: number | null;
            /**
             * @description URL of the thumbnail, as a signed internal-preview delivery URL.
             *
             *     Absolute when the deployment configures `server.public_url`, root-relative otherwise — so a client on a
             *     different origin must resolve it against the API's base rather than its own. Absent when the asset has
             *     no thumbnail yet, which is the normal state between an upload finishing and the worker deriving it: a
             *     URL minted regardless would 404, and a grid cannot tell a broken link from work still in progress.
             */
            thumbnail_url?: string | null;
            /**
             * @description Where the original lives, derived server-side from storage class and restore state so the UI
             *     never reimplements that mapping.
             */
            tier: components["schemas"]["AssetTier"];
            /**
             * Format: int32
             * @description Display dimensions — orientation already applied, so a grid cell can lay out from these
             *     without knowing about EXIF. `None` for formats with no intrinsic size.
             */
            width?: number | null;
        };
        /**
         * @description The tier a user sees.
         *
         *     Derived from two independent columns — the object's storage class and the state of any restore —
         *     and derived **here** rather than in the UI, because the mapping contains a trap: a restore does not
         *     change an object's storage class, so an *expired* restore of an archived object is archived again.
         *     The schema says so twice, and reimplementing the rule in TypeScript is how a download button stays
         *     enabled until the day someone presses it.
         * @enum {string}
         */
        AssetTier: "hot" | "cool" | "archive" | "restoring" | "restored";
        /** @description Which type an asset has, and the form that follows from it. */
        AssetTypeView: {
            /**
             * @description The fields that apply *now*, in order — the resolved answer rather than the stored pointer, because
             *     this is what the client has to draw.
             */
            field_keys: string[];
            /**
             * Format: uuid
             * @description `None` means the asset falls back — to the tenant's default type, or to the whole vocabulary when
             *     there is no default. Either way it still has a form; see `dam_db::metadata_types`.
             */
            metadata_type_id?: string | null;
            metadata_type_key?: string | null;
        };
        /** @description One facet bucket. */
        Bucket: {
            /** Format: int64 */
            count: number;
            /**
             * Format: uuid
             * @description A stable identifier where one exists — a taxonomy term id. Absent for a metadata value, whose identity
             *     *is* its text.
             */
            id?: string | null;
            /**
             * @description The value as text. A number or a boolean is rendered rather than typed, because a rail displays it and
             *     the round trip back into a query goes through the field's kind anyway.
             */
            value: string;
        };
        /** @description One failed row, for the report. */
        BulkFailure: {
            /** Format: uuid */
            asset_id: string;
            reason?: string | null;
        };
        /** @description What a preview reports. */
        BulkPreview: {
            kind: string;
            /**
             * Format: int64
             * @description How many of the submitted ids fell out of scope. Reported as a count and nothing more: which ones,
             *     and whether they exist at all, is exactly what §7 says a caller must not learn.
             */
            out_of_scope: number;
            /** @description A sample of the targets, for a dialog to name a few rather than list thousands. */
            sample: string[];
            /**
             * Format: int64
             * @description How many assets the operation would touch — after the caller's own scope is applied, so it is the
             *     number that will actually be touched.
             */
            target_count: number;
        };
        /** @description What a client asks for. */
        BulkRequest: {
            /** @description The selection. Deduplicated server-side; ids the caller may not manage fall out silently. */
            asset_ids: string[];
            /** @description `metadata_set` or `delete`. */
            kind: string;
            /**
             * @description Kind-specific parameters — for `metadata_set`, `{ "values": { … } }` with the same patch semantics
             *     as the single-asset endpoint: `null` clears, absent leaves alone.
             */
            params?: unknown;
        };
        /** @description An operation as the UI polls it. */
        BulkStatus: {
            /** Format: int64 */
            done_count: number;
            /** Format: int64 */
            failed_count: number;
            /** @description The first failures, row by row — "must report exactly which rows did not apply". */
            failures: components["schemas"]["BulkFailure"][];
            /** Format: uuid */
            id: string;
            kind: string;
            /** @description `queued`, `running`, `completed`, `partial`, `failed`, `cancelled`. */
            state: string;
            /** Format: int64 */
            target_count: number;
            /** @description Whether the state is final, so a client polls this instead of re-implementing the state vocabulary. */
            terminal: boolean;
        };
        /** @description A category to create within a tree. */
        CreateNodeRequest: {
            label: string;
            /**
             * Format: uuid
             * @description `None` makes it a root.
             */
            parent_id?: string | null;
            slug: string;
        };
        /** @description A tree to create. */
        CreateTreeRequest: {
            key: string;
            label: string;
        };
        /** @description A created share. The token appears here and nowhere else, exactly like an issued API key. */
        CreatedShare: {
            /** Format: uuid */
            id: string;
            /** @description The path a recipient opens, for the client to compose onto its own origin. */
            portal_path: string;
            /**
             * @description The one-time token. The table holds a digest, so a lost link cannot be recovered — revoke and
             *     re-create, which is the same posture as an API key and for the same reason.
             */
            token: string;
        };
        /** @description A field to define. Flags default to the conservative reading when omitted. */
        DefineRequest: {
            ai_writable?: boolean;
            facetable?: boolean;
            key: string;
            kind: string;
            label: string;
            multivalued?: boolean;
            read_only?: boolean;
            required?: boolean;
            search_alias?: string | null;
            /** @description Defaults to true: a field nobody can search for is the surprising choice, not the safe one. */
            searchable?: boolean;
            /** Format: uuid */
            taxonomy_id?: string | null;
            validation?: unknown;
        };
        /** @description A metadata type to create. */
        DefineTypeRequest: {
            applies_to?: string[];
            field_keys?: string[];
            is_default?: boolean;
            key: string;
            label: string;
        };
        /** @description One facetable field and its buckets. */
        Facet: {
            buckets: components["schemas"]["Bucket"][];
            key: string;
            /** @description Whether buckets were dropped by the limit. Reported rather than left implicit — see [`FACET_BUCKETS`]. */
            truncated: boolean;
        };
        /** @description One field definition, as a form needs it. */
        FieldDefinition: {
            /** @description Whether an enrichment run may write it. */
            ai_writable: boolean;
            facetable: boolean;
            key: string;
            /** @description The database spelling of the kind, so a client can pick an input type. */
            kind: string;
            /** @description The tenant's own label. A form shows this rather than the key. */
            label: string;
            /**
             * @description Whether the field takes an array.
             *
             *     Load-bearing rather than informational: a client that does not know this sends a comma-joined string
             *     to a field that takes an array, and the server refuses it with a message about delimiters that the
             *     user cannot act on. Discovered exactly that way, editing a multivalued field in a real browser.
             */
            multivalued: boolean;
            /** @description Set by ingest or by a connector; an editor must not offer it. */
            read_only: boolean;
            required: boolean;
            /** @description The shorthand prefix, when the tenant defined one: `bra:acme` for `brand`. */
            search_alias?: string | null;
            /** Format: uuid */
            taxonomy_id?: string | null;
        };
        /**
         * @description How long a `GET` takes to become possible.
         *
         *     The download path and the UI branch on **this**, not on the provider name. That is
         *     what lets Azure Archive or LTO tape slot in later without special-casing (§6.1).
         * @enum {string}
         */
        LatencyClass: "instant" | "seconds" | "minutes" | "hours" | "days";
        /** @description The outcome of a metadata edit. */
        MetadataAccepted: {
            /**
             * @description The stored document after the merge, so a client does not have to guess what the validator
             *     normalised — a date reformatted or a number coerced would otherwise show up as an unexplained diff
             *     on the next read.
             */
            values: unknown;
        };
        /** @description A metadata edit: the fields to change, keyed by definition key. */
        MetadataPatch: {
            /**
             * @description A merge, not a replacement. `null` for a value clears that field; a key that is absent is left
             *     alone. Two clients editing different fields of one asset must not overwrite each other, and a PUT of
             *     the whole document guarantees they do.
             */
            values: {
                [key: string]: unknown;
            };
        };
        /** @description A metadata type, with the count that decides whether editing it is safe. */
        MetadataTypeRow: {
            /** @description The media classes this type is the natural choice for at ingest. */
            applies_to: string[];
            /**
             * Format: int64
             * @description How many live assets currently carry this type.
             *
             *     On the row for the same reason a field's usage count is: removing a type re-forms every asset that
             *     referenced it, and an administrator should not have to go and ask how many that is.
             */
            assets: number;
            /** @description Its fields, in its own order. */
            field_keys: string[];
            /** Format: uuid */
            id: string;
            is_default: boolean;
            key: string;
            label: string;
        };
        /** @description One node, with the count of assets the caller can see at or beneath it. */
        NodeRow: {
            /**
             * Format: int64
             * @description Distinct assets **this caller** can see in this category or any beneath it.
             */
            assets: number;
            /** @description Depth, so a client indents without parsing `path`. */
            depth: number;
            /** Format: uuid */
            id: string;
            label: string;
            /** Format: uuid */
            parent_id?: string | null;
            /**
             * @description The ltree path. Exposed because the descendant filter uses it, and a client linking to a subtree
             *     should not need another round trip to learn it.
             */
            path: string;
            retired: boolean;
            slug: string;
        };
        /** @description The complete field order, in the order fields should appear. */
        OrderRequest: {
            keys: string[];
        };
        /**
         * @description Lifecycle state of one `object_placements` row.
         *
         *     Mirrors the `object_placements.state` CHECK. In `dam-core` rather than `dam-store`
         *     because both the database layer that loads it and the resolution layer that acts on it
         *     need the same vocabulary — and a second definition is how the two drift.
         *
         *     Only `Present` is readable. The others each mean something different to an operator,
         *     which is why this is not a boolean: `Uploading` will resolve itself, `Missing` needs a
         *     re-replication, `Corrupt` needs a scrub, and `Deleting` is expected to disappear.
         * @enum {string}
         */
        PlacementState: "uploading" | "present" | "transitioning" | "missing" | "corrupt" | "deleting";
        /** @description The download response. */
        PortalDownload: {
            /** Format: int32 */
            downloads_remaining?: number | null;
            /** @description A short-lived delivery URL. Fetch it promptly; the token, not this URL, is what the recipient keeps. */
            url: string;
        };
        /**
         * @description What a recipient sends. POST rather than GET even for the first look, so the passcode travels in a body —
         *     a passcode in a query string is a passcode in every proxy log on the path.
         */
        PortalRequest: {
            passcode?: string | null;
        };
        /** @description What the portal shows. */
        PortalView: {
            /** Format: int64 */
            bytes: number;
            download_allowed: boolean;
            /** Format: int32 */
            downloads_remaining?: number | null;
            /** Format: date-time */
            expires_at?: string | null;
            filename: string;
            /** Format: int32 */
            height?: number | null;
            mime: string;
            /** @description Why there is no preview, when there is a stateable reason. */
            preview_unavailable?: string | null;
            /**
             * @description A short-lived delivery URL for the web rendition — a full rights-checked distribution, `None` when
             *     rights refuse or no rendition exists yet. The share existing does not entitle anyone to pixels.
             */
            preview_url?: string | null;
            /** Format: int32 */
            width?: number | null;
        };
        /**
         * @description Content-credential verification outcome. Mirrors the `assets.provenance_state` CHECK.
         *
         *     Four states rather than a boolean because they call for different responses: `None` is a file that
         *     never had a credential, `Invalid` is one whose credential no longer matches its bytes, and
         *     `Untrusted` is an intact credential from a signer outside any trust list. Collapsing them loses
         *     the distinction between "no claim was made" and "a claim was made and broken".
         * @enum {string}
         */
        ProvenanceState: "none" | "valid" | "invalid" | "untrusted";
        /** @description Where a query was refused, so a UI can point at the character. */
        QueryProblem: {
            /**
             * @description One-based column the parser stopped at, when it has one. A filter rail underlines from here; without it
             *     a user gets "invalid query" and no idea which word.
             */
            at?: number | null;
            /**
             * @description A stable machine-readable code, when the parser gave one. A UI maps it to a message in the user's
             *     language, which prose cannot be.
             */
            code?: string | null;
            message: string;
        };
        /** @description What a removal did. */
        RemovedField: {
            /**
             * Format: int64
             * @description How many assets still carry a value under this key. The values are **kept** — see `dam_db`'s
             *     `fields::remove` — so this is what has gone invisible, not what was destroyed.
             */
            assets_with_values: number;
            key: string;
            reindex_required: boolean;
        };
        /**
         * @description Where a restore has got to, matching `object_placements.restore_state`.
         * @enum {string}
         */
        RestoreState: "none" | "requested" | "ongoing" | "available" | "expired";
        /**
         * @description Retrieval speed for a restore, matching `restore_requests.tier`.
         * @enum {string}
         */
        RestoreTier: "expedited" | "standard" | "bulk";
        /**
         * @description Rights evaluation outcome for an asset. Mirrors the `assets.rights_state` CHECK.
         * @enum {string}
         */
        RightsState: "allowed" | "expiring" | "denied" | "unknown";
        /** @description A field definition with the numbers an administrator needs before touching it. */
        SchemaField: {
            ai_writable: boolean;
            /**
             * Format: int64
             * @description How many live assets carry a value under this key.
             *
             *     The number that decides whether an edit is safe, so it is on the row rather than behind another
             *     request: an administrator deciding whether to remove a field should not have to go and ask.
             */
            assets_with_values: number;
            facetable: boolean;
            key: string;
            kind: string;
            label: string;
            multivalued: boolean;
            read_only: boolean;
            required: boolean;
            search_alias?: string | null;
            searchable: boolean;
            /** Format: uuid */
            taxonomy_id?: string | null;
        };
        /** @description What to set an asset's type to. `null` clears it, which is different from omitting the member. */
        SetAssetTypeRequest: {
            /** Format: uuid */
            metadata_type_id?: string | null;
        };
        /** @description What a client asks for when sharing an asset. */
        ShareRequest: {
            /** @description Whether the recipient may fetch the original, rather than only the web rendition. */
            allow_original?: boolean;
            /** Format: uuid */
            asset_id: string;
            /**
             * Format: int64
             * @description Hours until the link stops working. Absent means no expiry — revocation is then the only way it ends.
             */
            expires_in_hours?: number | null;
            /** Format: int32 */
            max_downloads?: number | null;
            /** @description Plaintext; hashed with argon2id server-side and never stored or returned. */
            passcode?: string | null;
        };
        /** @description One row in the management list. */
        ShareRow: {
            allow_original: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            download_count: number;
            /** Format: date-time */
            expires_at?: string | null;
            filename?: string | null;
            has_passcode: boolean;
            /** Format: uuid */
            id: string;
            /** @description Whether the link still works, so the list does not make a reader re-derive it from four columns. */
            live: boolean;
            /** Format: int32 */
            max_downloads?: number | null;
            revoked: boolean;
        };
        /**
         * @description The orders a client may ask for.
         *
         *     A closed set on the wire as well as in SQL. Accepting a column name would make the ORDER BY
         *     caller-supplied, and validating one against a list is the same list written twice.
         * @enum {string}
         */
        SortOrder: "newest" | "oldest" | "filename_asc" | "filename_desc" | "largest_first";
        /**
         * @description S3 storage classes, matching `object_placements.storage_class`.
         * @enum {string}
         */
        StorageClass: "STANDARD" | "STANDARD_IA" | "ONEZONE_IA" | "INTELLIGENT_TIERING" | "GLACIER_IR" | "GLACIER" | "DEEP_ARCHIVE";
        /** @description A category tree. */
        TreeRow: {
            /** Format: uuid */
            id: string;
            key: string;
            label: string;
        };
        /** @description Why an edit was refused, field by field. */
        ValidationProblem: {
            /**
             * @description A stable machine-readable code. Stable because a client branches on it and a UI maps it to a message
             *     in the user's language, neither of which can be done with prose.
             */
            code: string;
            detail: string;
            /** @description The payload key, or the field key for a missing required field. */
            key: string;
        };
        /** @description How many assets are in no category, and some of them. */
        Worklist: {
            /** @description The first few, so a client can link straight into them. */
            sample: string[];
            /**
             * Format: int64
             * @description Every uncategorised asset this caller can see.
             */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: {
                /** @description Zero-based index of the first row wanted. A virtualised grid sends the window it is about to draw. */
                offset?: number;
                /** @description Rows wanted. Clamped server-side; see `dam_db::assets::MAX_LIMIT`. */
                limit?: number;
                order?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page, with the total counted under the caller's own scope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetPage"];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no read scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The asset */
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no read scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such asset, or not one this caller may see — deliberately the same answer */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    of_asset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeRow"][];
                };
            };
        };
    };
    file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The asset's categories after filing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeRow"][];
                };
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description That category does not exist, or is retired */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The asset's categories after unfiling */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeRow"][];
                };
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The asset */
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetadataPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataAccepted"];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such asset, or not one this caller may see */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The payload failed validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"][];
                };
            };
        };
    };
    read_asset_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetTypeView"];
                };
            };
        };
    };
    set_asset_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAssetTypeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetTypeView"];
                };
            };
            /** @description No such type */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkRequest"];
            };
        };
        responses: {
            /** @description Accepted; poll the returned operation */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkStatus"];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The kind is not executable, or nothing in the selection is manageable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkRequest"];
            };
        };
        responses: {
            /** @description What the operation would touch, under the caller's own scope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkPreview"];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The kind is not executable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The operation */
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkStatus"];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such operation */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_trees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeRow"][];
                };
            };
        };
    };
    create_tree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTreeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeRow"];
                };
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_tree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeRow"][];
                };
            };
            /** @description No such category tree */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNodeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeRow"];
                };
            };
            /** @description No such category tree */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A sibling already uses that slug */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uncategorised: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worklist"];
                };
            };
            /** @description No such category tree */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fields: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every field definition, in display order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldDefinition"][];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no read scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaField"][];
                };
            };
            /** @description Authenticated, and holds no read scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    define: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefineRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaField"];
                };
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The key or alias is already taken; `reason` says which */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The key or kind is not usable; `reason` says why */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reorder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Reordered */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The list does not name every field exactly once */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemovedField"];
                };
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No field with that key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    amend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmendRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmendedField"];
                };
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No field with that key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stored values or a taken alias refuse the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The kind or taxonomy is not usable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataTypeRow"][];
                };
            };
        };
    };
    define_type: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefineTypeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataTypeRow"];
                };
            };
            /** @description The key is already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A named field does not exist */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such type */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    amend_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmendTypeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataTypeRow"];
                };
            };
            /** @description No such type */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A named field does not exist */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search: {
        parameters: {
            query?: {
                /** @description Shorthand: `bra:acme`, quoted phrases, ranges, negation. Empty matches everything the caller may see. */
                q?: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of ranked results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetPage"];
                };
            };
            /** @description The query does not parse, or names a field that does not exist */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryProblem"];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no read scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A clause the index cannot answer — refused rather than dropped, because dropping it would return more than was asked for */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryProblem"];
                };
            };
        };
    };
    facets: {
        parameters: {
            query?: {
                /** @description Shorthand: `bra:acme`, quoted phrases, ranges, negation. Empty matches everything the caller may see. */
                q?: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every facetable field with its buckets and counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facet"][];
                };
            };
            /** @description The query does not parse */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryProblem"];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no read scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    portal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalView"];
                };
            };
            /** @description A passcode is required or wrong; the body's `reason` says which */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such share — or revoked, expired, exhausted; the body's `reason` says which */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalDownload"];
                };
            };
            /** @description A passcode is required or wrong */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rights refuse distribution of this asset */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such share — or revoked, expired, exhausted */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareRow"][];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareRequest"];
            };
        };
        responses: {
            /** @description Created; the token appears here and nowhere else */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedShare"];
                };
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such asset, or not one this caller may manage */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The share */
                share_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked, or already was — revocation is idempotent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No usable credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated, and holds no manage scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
