//! Object keys.
//!
//! Keys are generated by damrs, never supplied by a caller — the layout is
//! content-addressed (§6.2), so a key is derived from a tenant id and a BLAKE3 hash.
//! Validation is therefore about catching *our own* bugs rather than defending against
//! hostile input: a key with a leading slash or a `..` segment is a construction
//! mistake that would silently write to the wrong prefix, and finding it at the type
//! boundary beats finding it in a bucket listing.

use crate::Error;
use dam_core::StorageClass;
use std::fmt;
use uuid::Uuid;

/// A validated object key.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Key(String);

/// Whether `upload_id` is a shape this system ever issues.
///
/// Public because the rule has two consumers and must not be written twice. [`Key::staging`] applies it
/// so a hostile id cannot steer a write outside its tenant prefix; the HTTP layer applies it at the edge
/// so a hostile id never reaches the database at all. That second use is not belt-and-braces — a NUL
/// byte in an id is rejected by Postgres itself, which surfaced as a `500` where a `404` belonged, and a
/// status that differs by input is the disclosure the 404-for-everything rule exists to prevent.
///
/// Alphanumeric, `-` and `_`: a superset of the hex ids we generate, chosen so a ULID or a UUID in any
/// common rendering passes, and nothing that means anything to a path, a shell, or a query does.
pub fn validate_upload_id(upload_id: &str) -> Result<(), Error> {
    if upload_id.is_empty() || upload_id.len() > 64 {
        return Err(Error::Backend(format!(
            "upload id must be 1-64 characters, got {}",
            upload_id.len()
        )));
    }
    if !upload_id
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err(Error::Backend(format!(
            "upload id must be alphanumeric, '-' or '_': {upload_id:?}"
        )));
    }
    Ok(())
}

impl Key {
    /// Validates and wraps.
    pub fn new(s: impl Into<String>) -> Result<Self, Error> {
        let s = s.into();
        if s.is_empty() {
            return Err(Error::Backend("object key must not be empty".into()));
        }
        if s.len() > 1024 {
            // S3's own limit. Hitting it means a key-construction bug, since our
            // longest layout is well under 200 bytes.
            return Err(Error::Backend(format!(
                "object key too long ({} bytes, max 1024)",
                s.len()
            )));
        }
        if s.starts_with('/') || s.ends_with('/') {
            return Err(Error::Backend(format!(
                "object key must not start or end with '/': {s:?}"
            )));
        }
        if s.split('/')
            .any(|seg| seg.is_empty() || seg == "." || seg == "..")
        {
            // `..` in an S3 key is legal but produces a path that tools resolve
            // differently, and an empty segment silently collapses. Both are bugs.
            return Err(Error::Backend(format!(
                "object key must not contain empty, '.' or '..' segments: {s:?}"
            )));
        }
        if s.chars().any(|c| c.is_control()) {
            return Err(Error::Backend(
                "object key contains control characters".into(),
            ));
        }
        Ok(Self(s))
    }

    /// The original master: `<tenant>/o/<aa>/<bb>/<blake3>`.
    ///
    /// The two-level fan-out exists because a flat prefix of millions of keys makes
    /// `ListObjectsV2` pagination miserable and defeats S3's internal partitioning.
    pub fn original(tenant: Uuid, blake3_hex: &str) -> Result<Self, Error> {
        let h = Self::validated_hash(blake3_hex)?;
        Self::new(format!("{tenant}/o/{}/{}/{h}", &h[0..2], &h[2..4]))
    }

    /// The master proxy: the AI and preview substrate that never tiers (§2).
    pub fn proxy(tenant: Uuid, blake3_hex: &str, ext: &str) -> Result<Self, Error> {
        let h = Self::validated_hash(blake3_hex)?;
        Self::new(format!("{tenant}/p/{h}/proxy.{ext}"))
    }

    /// A derivative, keyed on the operation hash so two assets producing identical
    /// renditions share one object.
    pub fn derivative(
        tenant: Uuid,
        blake3_hex: &str,
        op_hash: &str,
        ext: &str,
    ) -> Result<Self, Error> {
        let h = Self::validated_hash(blake3_hex)?;
        Self::new(format!("{tenant}/d/{h}/{op_hash}.{ext}"))
    }

    /// A thumbnail. Its own prefix so the lifecycle engine can pin the whole namespace
    /// without consulting the database — thumbnails must never tier, because the
    /// 128 KiB minimum billable size makes a 20 KB object cost more in IA than in
    /// Standard.
    pub fn thumbnail(tenant: Uuid, blake3_hex: &str, size: u32) -> Result<Self, Error> {
        let h = Self::validated_hash(blake3_hex)?;
        Self::new(format!("{tenant}/t/{h}/{size}.avif"))
    }

    /// A detached C2PA manifest, stored separately so a credential survives its
    /// master being tiered to Deep Archive (D13).
    pub fn manifest(tenant: Uuid, blake3_hex: &str) -> Result<Self, Error> {
        let h = Self::validated_hash(blake3_hex)?;
        Self::new(format!("{tenant}/c2pa/{h}/manifest.c2pa"))
    }

    /// A streamed upload before its digest is known: `<tenant>/staging/<upload_id>`.
    ///
    /// Its own namespace so a reaper can find abandoned uploads by prefix without consulting
    /// the database — an upload that died mid-stream may have no row at all.
    ///
    /// `upload_id` is ours (a ULID), not a client's, so it is validated as strictly as a
    /// digest: a client-supplied id would make this the one place a caller could steer a
    /// write outside its own prefix.
    pub fn staging(tenant: Uuid, upload_id: &str) -> Result<Self, Error> {
        validate_upload_id(upload_id)?;
        Self::new(format!("{tenant}/staging/{upload_id}"))
    }

    /// Whether this key is in a namespace the lifecycle engine must never tier.
    ///
    /// Derived from the key rather than looked up, so the rule holds even for an object
    /// whose placement row is missing or stale.
    pub fn is_tier_exempt(&self) -> bool {
        let Some((_, rest)) = self.0.split_once('/') else {
            return false;
        };
        // p/ = master proxy, t/ = thumbnails, c2pa/ = detached manifests,
        // staging/ = an upload in flight, which lives for minutes.
        rest.starts_with("p/")
            || rest.starts_with("t/")
            || rest.starts_with("c2pa/")
            || rest.starts_with("staging/")
    }

    /// The class this key may be tiered to, if any.
    pub fn permitted_class(&self, requested: StorageClass) -> StorageClass {
        if self.is_tier_exempt() {
            StorageClass::Standard
        } else {
            requested
        }
    }

    fn validated_hash(hex: &str) -> Result<&str, Error> {
        if hex.len() != 64 || !hex.chars().all(|c| c.is_ascii_hexdigit()) {
            return Err(Error::Backend(format!(
                "expected a 64-character hex BLAKE3 digest, got {} characters",
                hex.len()
            )));
        }
        if hex.chars().any(|c| c.is_ascii_uppercase()) {
            // Lowercase only: an uppercase digest would produce a second key for the
            // same content, defeating the deduplication the layout exists for.
            return Err(Error::Backend("BLAKE3 digest must be lowercase hex".into()));
        }
        Ok(hex)
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    pub fn into_string(self) -> String {
        self.0
    }
}

impl fmt::Display for Key {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const H: &str = "9f2a1b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f8";

    fn tenant() -> Uuid {
        Uuid::nil()
    }

    #[test]
    fn the_original_layout_fans_out_two_levels() {
        let k = Key::original(tenant(), H).expect("key");
        assert_eq!(
            k.as_str(),
            format!("00000000-0000-0000-0000-000000000000/o/9f/2a/{H}")
        );
    }

    #[test]
    fn proxies_thumbnails_and_manifests_are_tier_exempt_but_originals_are_not() {
        assert!(!Key::original(tenant(), H).expect("k").is_tier_exempt());
        assert!(Key::proxy(tenant(), H, "jpg").expect("k").is_tier_exempt());
        assert!(
            Key::thumbnail(tenant(), H, 400)
                .expect("k")
                .is_tier_exempt()
        );
        assert!(Key::manifest(tenant(), H).expect("k").is_tier_exempt());
        assert!(
            Key::staging(tenant(), "01J8Z9QX4E")
                .expect("k")
                .is_tier_exempt(),
            "a staging object is deleted within minutes; a minimum-duration charge on it \
             is pure waste"
        );
        // A derivative is not exempt: a rare 40-minute ProRes export is worth tiering.
        assert!(
            !Key::derivative(tenant(), H, "abc", "mov")
                .expect("k")
                .is_tier_exempt()
        );
    }

    #[test]
    fn an_exempt_key_cannot_be_tiered_even_if_asked() {
        let proxy = Key::proxy(tenant(), H, "jpg").expect("k");
        assert_eq!(
            proxy.permitted_class(StorageClass::DeepArchive),
            StorageClass::Standard,
            "the proxy is the AI substrate and must stay hot"
        );
        let original = Key::original(tenant(), H).expect("k");
        assert_eq!(
            original.permitted_class(StorageClass::DeepArchive),
            StorageClass::DeepArchive
        );
    }

    #[test]
    fn an_upload_id_cannot_steer_a_write_out_of_its_prefix() {
        for bad in ["", "../../etc", "has/slash", "spaces here", &"x".repeat(65)] {
            assert!(
                Key::staging(tenant(), bad).is_err(),
                "{bad:?} must be rejected as an upload id"
            );
        }
        assert!(Key::staging(tenant(), "01J8Z9QX4E7N2VYB3K6M5T8W1R").is_ok());
    }

    #[test]
    fn malformed_keys_are_rejected() {
        for bad in [
            "",
            "/leading",
            "trailing/",
            "double//slash",
            "has/../dotdot",
            "has/./dot",
            "control\u{1}char",
        ] {
            assert!(Key::new(bad).is_err(), "{bad:?} should be rejected");
        }
    }

    #[test]
    fn a_digest_must_be_64_lowercase_hex_characters() {
        assert!(Key::original(tenant(), "abc").is_err(), "too short");
        assert!(
            Key::original(tenant(), &H.to_uppercase()).is_err(),
            "uppercase would produce a second key for the same content"
        );
        assert!(Key::original(tenant(), &"g".repeat(64)).is_err(), "not hex");
    }

    #[test]
    fn keys_sort_lexicographically_for_prefix_listing() {
        let mut keys = [
            Key::new("t/o/bb").expect("k"),
            Key::new("t/o/aa").expect("k"),
        ];
        keys.sort();
        assert_eq!(keys[0].as_str(), "t/o/aa");
    }
}
