//! Recording content credentials (1.9), and the invariant that proves the pipeline kept them.
//!
//! `dam_media::provenance` verifies and signs; this stores the result. The split matters because the
//! *storage* is where D13 is actually enforceable: a manifest that was verified and then not written
//! down is a manifest lost at the next restart, and G1's regression — a derivative served without the
//! credentials its master had — is a cross-table condition that only the database can see.
//!
//! That condition already exists as the `provenance_gaps` view. [`gaps`] queries it, and it is meant to
//! be wired to an alert rather than a dashboard nobody opens: a non-empty result means a customer is
//! being served credential-stripped renditions of content they hold credentials for, which downgrades
//! their asset without telling them.
//!
//! ## Why the manifest is a separate object
//!
//! §2 keeps metadata hot while masters tier to Deep Archive. A credential that lived only inside the
//! original's bytes would become unverifiable the moment the original was archived — so the manifest
//! gets its own key under the `c2pa/` prefix, which `Key::is_tier_exempt` already refuses to tier.

use crate::Error;
use chrono::{DateTime, Utc};
use uuid::Uuid;

/// A manifest as stored.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StoredManifest {
    pub id: Uuid,
    pub role: Role,
    pub object_key: String,
    pub bytes: i64,
    pub validation_state: String,
    pub signer_cn: Option<String>,
    pub claim_generator: Option<String>,
    pub parent_manifest_id: Option<Uuid>,
}

/// Which side of the chain a manifest is on.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Role {
    /// As received. Never modified — it is the customer's evidence, including when it fails to verify.
    Inbound,
    /// Generated by us for a derivative, chaining to the inbound one.
    DamrsSigned,
}

impl Role {
    fn as_str(self) -> &'static str {
        match self {
            Self::Inbound => "inbound",
            Self::DamrsSigned => "damrs_signed",
        }
    }

    fn parse(raw: &str) -> Result<Self, Error> {
        match raw {
            "inbound" => Ok(Self::Inbound),
            "damrs_signed" => Ok(Self::DamrsSigned),
            other => Err(Error::Inconsistent(format!(
                "provenance_manifests.role holds {other:?}, which the CHECK constraint should have \
                 refused"
            ))),
        }
    }
}

/// What to write for a manifest.
#[derive(Debug, Clone)]
pub struct NewManifest<'a> {
    pub object_key: &'a str,
    pub bytes: i64,
    /// From `dam_core::rights::ProvenanceState::as_validation_state` — *not* `as_str`, which
    /// renders the `assets` column's vocabulary and spells the absent case `none` rather than `absent`.
    pub validation_state: &'a str,
    pub validation_detail: serde_json::Value,
    pub signer_cn: Option<&'a str>,
    pub claim_generator: Option<&'a str>,
    pub spec_version: Option<&'a str>,
    pub captured_at: Option<DateTime<Utc>>,
    /// Action labels in order, written to `provenance_actions`.
    ///
    /// Recorded relationally as well as inside the signed manifest, so "what did damrs do to this file"
    /// is a query — and so a manifest can be regenerated if a signing certificate is rotated or a blob
    /// is lost.
    pub actions: Vec<String>,
}

/// Records the manifest an asset arrived with.
///
/// Also sets `assets.had_inbound_manifest` and `assets.provenance_state`, in the same transaction. That
/// is the point: `had_inbound_manifest` is what makes a later missing derivative manifest detectable as
/// a *bug* rather than an absence, so a flow that recorded the manifest without setting the flag would
/// disable the very alarm this exists to arm.
pub async fn record_inbound<'e, E>(
    executor: E,
    asset_id: Uuid,
    manifest: &NewManifest<'_>,
) -> Result<Uuid, Error>
where
    E: sqlx::PgExecutor<'e> + Copy,
{
    let id = Uuid::new_v4();
    insert(
        executor,
        id,
        Some(asset_id),
        None,
        Role::Inbound,
        None,
        manifest,
    )
    .await?;

    // `had_inbound_manifest` is set for a failed manifest too — decision C2PA 3. The asset *did* arrive
    // with credentials; that they are broken is what `provenance_state` says, and it does not make the
    // derivative-coverage requirement go away.
    sqlx::query(
        "UPDATE assets SET had_inbound_manifest = true, provenance_state = $2 WHERE id = $1",
    )
    .bind(asset_id)
    .bind(manifest.validation_state)
    .execute(executor)
    .await?;

    Ok(id)
}

/// Records a manifest damrs signed for a derivative, chained to `parent_manifest_id`.
///
/// The chain link is a parameter rather than something looked up here, because the caller is the one
/// that knows which manifest it actually chained to in the signed bytes. Deriving it from the asset
/// would let the row claim a lineage the manifest itself does not contain.
pub async fn record_signed<'e, E>(
    executor: E,
    derivative_id: Uuid,
    parent_manifest_id: Option<Uuid>,
    manifest: &NewManifest<'_>,
) -> Result<Uuid, Error>
where
    E: sqlx::PgExecutor<'e> + Copy,
{
    let id = Uuid::new_v4();
    insert(
        executor,
        id,
        None,
        Some(derivative_id),
        Role::DamrsSigned,
        parent_manifest_id,
        manifest,
    )
    .await?;
    Ok(id)
}

async fn insert<'e, E>(
    executor: E,
    id: Uuid,
    asset_id: Option<Uuid>,
    derivative_id: Option<Uuid>,
    role: Role,
    parent_manifest_id: Option<Uuid>,
    manifest: &NewManifest<'_>,
) -> Result<(), Error>
where
    E: sqlx::PgExecutor<'e> + Copy,
{
    sqlx::query(
        "INSERT INTO provenance_manifests \
         (id, asset_id, derivative_id, role, object_key, bytes, parent_manifest_id, \
          validation_state, validation_detail, signer_cn, claim_generator, spec_version, \
          captured_at, verified_at) \
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now())",
    )
    .bind(id)
    .bind(asset_id)
    .bind(derivative_id)
    .bind(role.as_str())
    .bind(manifest.object_key)
    .bind(manifest.bytes)
    .bind(parent_manifest_id)
    .bind(manifest.validation_state)
    .bind(&manifest.validation_detail)
    .bind(manifest.signer_cn)
    .bind(manifest.claim_generator)
    .bind(manifest.spec_version)
    .bind(manifest.captured_at)
    .execute(executor)
    .await?;

    for (index, action) in manifest.actions.iter().enumerate() {
        let seq = i32::try_from(index).map_err(|_| {
            Error::Inconsistent("a manifest with more than 2^31 actions".to_owned())
        })?;
        sqlx::query(
            "INSERT INTO provenance_actions (id, manifest_id, seq, action, software_agent) \
             VALUES ($1, $2, $3, $4, $5)",
        )
        .bind(Uuid::new_v4())
        .bind(id)
        .bind(seq)
        .bind(action)
        .bind(manifest.claim_generator)
        .execute(executor)
        .await?;
    }
    Ok(())
}

/// Loads an asset's manifests, inbound first.
pub async fn for_asset<'e, E>(executor: E, asset_id: Uuid) -> Result<Vec<StoredManifest>, Error>
where
    E: sqlx::PgExecutor<'e>,
{
    let rows = sqlx::query_as::<
        _,
        (
            Uuid,
            String,
            String,
            i64,
            String,
            Option<String>,
            Option<String>,
            Option<Uuid>,
        ),
    >(
        "SELECT pm.id, pm.role, pm.object_key, pm.bytes, pm.validation_state, pm.signer_cn, \
                pm.claim_generator, pm.parent_manifest_id \
         FROM provenance_manifests pm \
         LEFT JOIN derivatives d ON d.id = pm.derivative_id \
         WHERE pm.asset_id = $1 OR d.asset_id = $1 \
         ORDER BY pm.role DESC, pm.created_at",
    )
    .bind(asset_id)
    .fetch_all(executor)
    .await?;

    rows.into_iter()
        .map(
            |(id, role, object_key, bytes, state, signer_cn, generator, parent)| {
                Ok(StoredManifest {
                    id,
                    role: Role::parse(&role)?,
                    object_key,
                    bytes,
                    validation_state: state,
                    signer_cn,
                    claim_generator: generator,
                    parent_manifest_id: parent,
                })
            },
        )
        .collect()
}

/// A derivative served without the credentials its master had.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Gap {
    pub derivative_id: Uuid,
    pub asset_id: Uuid,
    pub role: String,
    pub profile: String,
}

/// Every derivative that lost provenance the pipeline was supposed to preserve.
///
/// Should always be empty. A non-empty result is G1 regressing: a customer's credentialed content being
/// served as credential-stripped renditions, which is worse than not supporting C2PA at all because it
/// silently downgrades content they already had signed.
///
/// Reads the `provenance_gaps` view rather than restating its condition, so there is exactly one
/// definition of the invariant and a schema change cannot leave the Rust copy behind.
pub async fn gaps<'e, E>(executor: E, limit: i64) -> Result<Vec<Gap>, Error>
where
    E: sqlx::PgExecutor<'e>,
{
    let rows = sqlx::query_as::<_, (Uuid, Uuid, String, String)>(
        "SELECT derivative_id, asset_id, role, profile FROM provenance_gaps \
         ORDER BY created_at LIMIT $1",
    )
    .bind(limit)
    .fetch_all(executor)
    .await?;

    Ok(rows
        .into_iter()
        .map(|(derivative_id, asset_id, role, profile)| Gap {
            derivative_id,
            asset_id,
            role,
            profile,
        })
        .collect())
}
