//! A tenant's own C2PA signing identity (G10·3b).
//!
//! Everything here takes and returns the **sealed** key, never plaintext — the same contract
//! [`crate::ai_credentials`] holds, and for the same reason: sealing needs the deployment's keyring, which is
//! configuration this crate deliberately does not read. A caller seals, stores, reads back and opens; this
//! module only moves the sealed text.
//!
//! ## Why this exists at all
//!
//! One deployment signed every tenant's derivatives with one identity. That is correct for a dedicated
//! install and is the furthest-reaching of the four purposes to get wrong on a shared one, because a signing
//! identity is what a consumer *verifies against*. Two customers' assets signed by one certificate assert, to
//! anybody who checks, that they came from the same publisher.
//!
//! ## The certificate is public and the key is not
//!
//! `cert_pem` is handed to every verifier of every asset signed with it, so it is stored plainly and is not a
//! secret. `sealed_key` is bound to `{tenant}:signing:{id}`, so a row copied into another tenant's schema
//! fails to open rather than signing on their behalf.
//!
//! ## Superseded identities are kept
//!
//! A manifest signed last year is verified against the certificate that signed it. Deleting a superseded row
//! would not invalidate those signatures, but it would remove the only record of which identity produced
//! them — which is the question asked when a certificate turns out to have been mis-issued.

use crate::Error;
use chrono::{DateTime, Utc};
use uuid::Uuid;

/// The associated data an identity's key is sealed under.
///
/// `{tenant}:signing:{id}`. Every part is something a row cannot change without the key refusing to open:
/// moved to another tenant, relabelled, or copied to a new row — each fails closed.
#[must_use]
pub fn associated_data(tenant: &str, id: Uuid) -> String {
    format!("{tenant}:signing:{id}")
}

/// One identity. The key is sealed; the certificate is not a secret.
#[derive(Debug, Clone)]
pub struct SigningIdentity {
    pub id: Uuid,
    pub label: String,
    pub cert_pem: String,
    /// Sealed. Not a `Secret`, because it is not one — it is the ciphertext.
    pub sealed_key: String,
    pub sealing_key_id: String,
    pub algorithm: String,
    pub timestamp_authority: Option<String>,
    pub is_active: bool,
    pub created_at: DateTime<Utc>,
}

impl SigningIdentity {
    /// The associated data this row's key was sealed under.
    #[must_use]
    pub fn associated_data(&self, tenant: &str) -> String {
        associated_data(tenant, self.id)
    }
}

/// What to record for a new identity.
#[derive(Debug, Clone)]
pub struct NewIdentity<'a> {
    /// Generated by the caller, because the id is part of the associated data and so must be known before the
    /// key is sealed. A database-generated id would force a seal-then-update, and a failure between the two
    /// would leave a row whose ciphertext is bound to an id it does not have — the same reason
    /// [`crate::ai_credentials::NewCredential`] takes one.
    pub id: Uuid,
    pub label: &'a str,
    pub cert_pem: &'a str,
    /// Already sealed by the caller. See the module docs.
    pub sealed_key: &'a str,
    pub sealing_key_id: &'a str,
    pub algorithm: &'a str,
    pub timestamp_authority: Option<&'a str>,
}

fn row_to_identity(row: &sqlx::postgres::PgRow) -> Result<SigningIdentity, Error> {
    use sqlx::Row as _;
    Ok(SigningIdentity {
        id: row.try_get("id")?,
        label: row.try_get("label")?,
        cert_pem: row.try_get("cert_pem")?,
        sealed_key: row.try_get("sealed_key")?,
        sealing_key_id: row.try_get("sealing_key_id")?,
        algorithm: row.try_get("algorithm")?,
        timestamp_authority: row.try_get("timestamp_authority")?,
        is_active: row.try_get("is_active")?,
        created_at: row.try_get("created_at")?,
    })
}

/// The identity this tenant currently signs with, if it has one of its own.
///
/// `None` means the deployment's configured identity applies — the same falling-back shape
/// [`crate::encryption_keys::resolve`] uses, and for the same reason: a tenant with no identity of its own
/// must keep signing as it did rather than start producing unsigned derivatives.
///
/// # Errors
/// Any database failure.
pub async fn active(conn: &mut sqlx::PgConnection) -> Result<Option<SigningIdentity>, Error> {
    let row = sqlx::query(
        "SELECT id, label, cert_pem, sealed_key, sealing_key_id, algorithm, \
                timestamp_authority, is_active, created_at \
         FROM signing_identities WHERE is_active",
    )
    .fetch_optional(&mut *conn)
    .await?;
    row.as_ref().map(row_to_identity).transpose()
}

/// Every identity this tenant has had, newest first.
///
/// # Errors
/// Any database failure.
pub async fn list(conn: &mut sqlx::PgConnection) -> Result<Vec<SigningIdentity>, Error> {
    let rows = sqlx::query(
        "SELECT id, label, cert_pem, sealed_key, sealing_key_id, algorithm, \
                timestamp_authority, is_active, created_at \
         FROM signing_identities ORDER BY created_at DESC",
    )
    .fetch_all(&mut *conn)
    .await?;
    rows.iter().map(row_to_identity).collect()
}

/// Records an identity and makes it the one that signs.
///
/// The previous active row is stood down first, in the caller's transaction, because the partial unique index
/// refuses two active rows — and two round trips would leave a window where a renderer sees none and produces
/// an unsigned derivative.
///
/// # Errors
/// Any database failure.
pub async fn activate(
    conn: &mut sqlx::PgConnection,
    new: &NewIdentity<'_>,
) -> Result<SigningIdentity, Error> {
    sqlx::query(
        "UPDATE signing_identities SET is_active = false, updated_at = now() WHERE is_active",
    )
    .execute(&mut *conn)
    .await?;

    let row = sqlx::query(
        "INSERT INTO signing_identities \
         (id, label, cert_pem, sealed_key, sealing_key_id, algorithm, timestamp_authority) \
         VALUES ($1, $2, $3, $4, $5, $6, $7) \
         RETURNING id, label, cert_pem, sealed_key, sealing_key_id, algorithm, \
                   timestamp_authority, is_active, created_at",
    )
    .bind(new.id)
    .bind(new.label)
    .bind(new.cert_pem)
    .bind(new.sealed_key)
    .bind(new.sealing_key_id)
    .bind(new.algorithm)
    .bind(new.timestamp_authority)
    .fetch_one(&mut *conn)
    .await?;
    row_to_identity(&row)
}

/// Stands the active identity down without putting another in its place.
///
/// The tenant falls back to the deployment's identity rather than stopping signing — see [`active`]. Returns
/// whether there was one to stand down.
///
/// # Errors
/// Any database failure.
pub async fn deactivate(conn: &mut sqlx::PgConnection) -> Result<bool, Error> {
    let done = sqlx::query(
        "UPDATE signing_identities SET is_active = false, updated_at = now() WHERE is_active",
    )
    .execute(&mut *conn)
    .await?;
    Ok(done.rows_affected() == 1)
}
