//! Persistence and reaping for resumable uploads.
//!
//! [`dam_store::resumable`] is stateless by design: the session is a value the caller stores
//! and hands back, which is what lets any node serve any TUS PATCH and a restart lose nothing.
//! This module is the other half — the store, and the reaper.
//!
//! ## Why the reaper is not optional
//!
//! An abandoned multipart upload keeps its parts, and S3 bills for them until they are aborted
//! or a bucket lifecycle rule expires them. A DAM whose clients drop connections — which is
//! every DAM, because uploads are large and networks are not — accumulates that silently. The
//! reaper is what stops the meter, and the row is kept afterwards so a client asking about its
//! upload gets an answer rather than a 404.
//!
//! ## Executor-generic on the request path
//!
//! `create`, `load` and `save` take any `PgExecutor`, so they work against a pool *and* against a
//! [`crate::TenantConn`]'s connection. That matters: §5.2 makes `TenantConn` — one shared pool, a
//! per-request transaction with `SET LOCAL search_path` — the tenant-isolation mechanism, and a
//! function that only accepted a pool would force a pool per tenant instead. At a thousand tenants
//! that is a thousand connection pools.
//!
//! `reapable` and `reap` still take a pool, because they issue several statements in sequence and run
//! from the worker rather than from a request, where there is no transaction to join.
//!
//! ## Why the constraints are in the schema and not only here
//!
//! A session is written by one request and read by another. An inconsistent row does not fail
//! loudly; it assembles the **wrong bytes** under a content-addressed key, producing an object
//! that looks canonical. `0009_uploads.sql` refuses those rows, and
//! [`the_database_refuses_a_session_the_rust_should_never_have_built`] in the test suite is
//! what keeps the two definitions honest.

use crate::Error;
use dam_store::{
    ResumableStore,
    resumable::{PartRecord, ResumableSession, SessionStatus},
};
use serde_json::Value as Json;
use sqlx::{PgPool, Row, postgres::PgRow};
use uuid::Uuid;

/// Creates a session row and returns the value the engine works with.
///
/// `upload_id` is generated by the caller and becomes part of an object key, so it is validated
/// by `Key::staging` in Rust *and* by a CHECK in the schema.
#[allow(clippy::too_many_arguments)]
pub async fn create<'e, E>(
    executor: E,
    tenant: Uuid,
    upload_id: &str,
    declared_length: Option<u64>,
    declared_filename: Option<&str>,
    declared_mime: Option<&str>,
    created_by: Option<Uuid>,
    // The profile this upload was made under (Q.3), or `None` to let finalise fall back.
    upload_profile_id: Option<Uuid>,
) -> Result<ResumableSession, Error>
where
    E: sqlx::PgExecutor<'e>,
{
    let session = ResumableSession::new(upload_id.to_owned(), tenant, declared_length);
    // Rejects an id that could steer a write outside the tenant prefix before it reaches the
    // database, so the error names the real problem rather than a constraint number.
    session.staging_key().map_err(|e| {
        Error::Core(dam_core::Error::Validation {
            field: "upload_id".into(),
            reason: format!("{upload_id:?}: {e}"),
        })
    })?;

    sqlx::query(
        "INSERT INTO upload_sessions \
         (id, tenant_id, upload_id, status, offset_bytes, declared_length, declared_filename, \
          declared_mime, created_by, upload_profile_id) \
         VALUES (gen_random_uuid(), $1, $2, 'active', 0, $3, $4, $5, $6, $7)",
    )
    .bind(tenant)
    .bind(upload_id)
    .bind(declared_length.map(|v| v as i64))
    .bind(declared_filename)
    .bind(declared_mime)
    .bind(created_by)
    .bind(upload_profile_id)
    .execute(executor)
    .await?;

    Ok(session)
}

/// What the client said about the upload, plus what it became.
///
/// Read in one query rather than three. The three fields are wanted at the same moment — finalisation needs
/// the declared type to sniff against, the declared filename to record, and the asset id to know whether it
/// has already run — and three round trips inside one job is three chances to see a half-updated row.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Declared {
    /// Preserved verbatim: it is what the user called their file. Never trusted for the type.
    pub filename: Option<String>,
    /// Recorded for the audit trail. The stored mime is sniffed from the bytes.
    pub mime: Option<String>,
    /// The asset this session became, when it has been finalised.
    pub asset_id: Option<uuid::Uuid>,
    /// The upload profile this session named, if any (Q.3).
    ///
    /// Read here rather than passed to finalise, because finalise can run from a queue long after the request
    /// that created the session — the profile has to be recoverable from the row.
    pub upload_profile_id: Option<uuid::Uuid>,
    /// BLAKE3 of the promoted object, when the promotion has happened.
    ///
    /// Its presence means the bytes are already at their content-addressed key — which is what makes
    /// finalisation resumable across the gap between promoting an object and recording an asset. Those two
    /// cannot be one transaction, so without this a crash between them left the bytes stored and the retry
    /// failing at "staging object not found".
    pub content_hash: Option<String>,
    /// Who started the upload, when a person did (Q.7).
    ///
    /// Read here for the same reason as the profile: finalisation runs from a queue long after the request, so the
    /// feed entry's actor has to be recoverable from the row rather than passed in.
    pub created_by: Option<uuid::Uuid>,
}

/// The declared fields for one upload, or `None` if there is no such session.
pub async fn declared<'e, E>(
    executor: E,
    tenant: Uuid,
    upload_id: &str,
) -> Result<Option<Declared>, Error>
where
    E: sqlx::PgExecutor<'e>,
{
    let row = sqlx::query_as::<
        _,
        (
            Option<String>,
            Option<String>,
            Option<Uuid>,
            Option<String>,
            Option<Uuid>,
            Option<Uuid>,
        ),
    >(
        "SELECT declared_filename, declared_mime, asset_id, content_hash, upload_profile_id, created_by \
         FROM upload_sessions WHERE tenant_id = $1 AND upload_id = $2",
    )
    .bind(tenant)
    .bind(upload_id)
    .fetch_optional(executor)
    .await?;

    Ok(row.map(
        |(filename, mime, asset_id, content_hash, upload_profile_id, created_by)| Declared {
            filename,
            mime,
            asset_id,
            content_hash,
            upload_profile_id,
            created_by,
        },
    ))
}

/// Records the digest of a promoted upload.
///
/// Called the moment the promotion succeeds and before the asset row exists — see [`Declared::content_hash`].
pub async fn record_promotion<'e, E>(
    executor: E,
    tenant: Uuid,
    upload_id: &str,
    content_hash: &str,
) -> Result<(), Error>
where
    E: sqlx::PgExecutor<'e>,
{
    sqlx::query(
        "UPDATE upload_sessions SET content_hash = $3, updated_at = now() \
         WHERE tenant_id = $1 AND upload_id = $2",
    )
    .bind(tenant)
    .bind(upload_id)
    .bind(content_hash)
    .execute(executor)
    .await?;
    Ok(())
}

/// Loads a session, or `None` if there is no such upload.
///
/// Absence is a normal outcome — a client polling a completed upload's id arrives here — so it
/// is an `Option` rather than an error.
pub async fn load<'e, E>(
    executor: E,
    tenant: Uuid,
    upload_id: &str,
) -> Result<Option<ResumableSession>, Error>
where
    E: sqlx::PgExecutor<'e>,
{
    let row = sqlx::query(
        "SELECT tenant_id, upload_id, status, offset_bytes, declared_length, \
                backend_upload_id, part_count, tail_bytes, parts \
         FROM upload_sessions WHERE upload_id = $1 AND tenant_id = $2",
    )
    .bind(upload_id)
    .bind(tenant)
    .fetch_optional(executor)
    .await?;

    let Some(row) = row else { return Ok(None) };
    let session = from_row(&row)?;
    if session.tenant != tenant {
        // Unreachable through the query above, and kept anyway. The predicate is what makes a
        // wrong-tenant lookup return `None` — indistinguishable from a missing upload, which is
        // the answer the HTTP layer needs to avoid confirming that someone else's id exists. If
        // that predicate is ever edited away, this turns the resulting cross-tenant read into a
        // loud failure instead of a silent success.
        return Err(Error::Inconsistent(format!(
            "upload session {upload_id} belongs to tenant {} but was loaded as {tenant}",
            session.tenant
        )));
    }
    Ok(Some(session))
}

/// Writes the session's mutable state back.
///
/// Every field the engine advances, in one statement: an upload that recorded its offset but
/// not its parts would resume by re-sending bytes it already has.
pub async fn save<'e, E>(executor: E, session: &ResumableSession) -> Result<(), Error>
where
    E: sqlx::PgExecutor<'e>,
{
    // Built directly rather than via `to_value`, so encoding cannot fail and there is no
    // error path to invent a variant for.
    let parts = Json::Array(
        session
            .parts
            .iter()
            .map(|p| serde_json::json!({ "number": p.number, "etag": p.etag }))
            .collect(),
    );

    let affected = sqlx::query(
        "UPDATE upload_sessions SET \
            status = $2, offset_bytes = $3, declared_length = $4, backend_upload_id = $5, \
            part_count = $6, tail_bytes = $7, parts = $8, updated_at = now(), \
            completed_at = CASE WHEN $2 = 'completed' THEN coalesce(completed_at, now()) \
                                ELSE completed_at END \
         WHERE upload_id = $1",
    )
    .bind(&session.id)
    .bind(status_str(session.status))
    .bind(session.offset as i64)
    .bind(session.declared_length.map(|v| v as i64))
    .bind(session.s3_upload_id.as_deref())
    .bind(session.parts.len() as i32)
    .bind(session.tail_len as i64)
    .bind(parts)
    .execute(executor)
    .await?
    .rows_affected();

    if affected == 0 {
        // Not a no-op to be shrugged at: the caller believes it holds a live session, and
        // continuing would append to an upload the database has no record of.
        return Err(Error::UploadGone(session.id.clone()));
    }
    Ok(())
}

/// Expired sessions still holding storage, oldest first, capped at `limit`.
///
/// Only `active` rows: a completed session's bytes were promoted to a content-addressed key and
/// there is nothing to reclaim, and a terminated one has already been cleaned.
pub async fn reapable(pool: &PgPool, limit: i64) -> Result<Vec<ResumableSession>, Error> {
    let rows = sqlx::query(
        "SELECT tenant_id, upload_id, status, offset_bytes, declared_length, \
                backend_upload_id, part_count, tail_bytes, parts \
         FROM upload_sessions \
         WHERE status = 'active' AND expires_at <= now() \
         ORDER BY expires_at \
         LIMIT $1",
    )
    .bind(limit)
    .fetch_all(pool)
    .await?;

    // Each row carries its own tenant, which is what lets the reaper rebuild the staging key
    // without consulting the control plane.
    rows.iter().map(from_row).collect()
}

/// Reclaims every expired upload, returning how many were reaped.
///
/// Storage first, then the row. If the process dies between the two, the next pass finds the row
/// still `active` and repeats a cleanup that is idempotent — whereas marking the row first would
/// orphan the parts permanently, with nothing left pointing at them.
pub async fn reap<S: ResumableStore + ?Sized>(
    pool: &PgPool,
    store: &S,
    limit: i64,
) -> Result<u64, Error> {
    let due = reapable(pool, limit).await?;
    let mut reaped = 0u64;

    for mut session in due {
        if let Err(e) = dam_store::resumable::terminate(store, &mut session).await {
            // One stuck upload must not stop the batch: the next pass retries it, and a reaper
            // that aborts on the first failure stops reclaiming anything at all.
            tracing::warn!(
                upload_id = %session.id,
                error = %e,
                "could not reclaim storage for an expired upload; leaving it for the next pass"
            );
            continue;
        }

        sqlx::query(
            "UPDATE upload_sessions SET status = 'terminated', updated_at = now(), \
                    backend_upload_id = NULL, part_count = 0, tail_bytes = 0, \
                    parts = '[]'::jsonb \
             WHERE upload_id = $1 AND status = 'active'",
        )
        .bind(&session.id)
        .execute(pool)
        .await?;
        reaped += 1;
    }
    Ok(reaped)
}

/// Ages a session's expiry by `hours`, for tests only.
///
/// Time is not injectable through SQL `now()`, and a reaper test that slept for real would be
/// either slow or flaky. Kept behind an explicit name so it reads as test scaffolding at every
/// call site.
pub async fn force_expiry_for_test(
    pool: &PgPool,
    upload_id: &str,
    hours: i64,
) -> Result<(), Error> {
    sqlx::query("UPDATE upload_sessions SET expires_at = now() + make_interval(hours => $2::int) WHERE upload_id = $1")
        .bind(upload_id)
        .bind(hours as i32)
        .execute(pool)
        .await
        ?;
    Ok(())
}

fn from_row(row: &PgRow) -> Result<ResumableSession, Error> {
    let status = match row.get::<String, _>("status").as_str() {
        "active" => SessionStatus::Active,
        "completed" => SessionStatus::Completed,
        // `expired` is the schema's vocabulary for a session the reaper has not yet reached;
        // to the engine it is simply not resumable, which `Terminated` already means.
        "terminated" | "expired" => SessionStatus::Terminated,
        other => {
            return Err(Error::Inconsistent(format!(
                "upload session has unknown status {other:?}"
            )));
        }
    };

    let parts: Json = row.try_get("parts").unwrap_or_else(|_| Json::Array(vec![]));
    let parts = parts
        .as_array()
        .map(|items| {
            items
                .iter()
                .filter_map(|p| {
                    Some(PartRecord {
                        number: i32::try_from(p.get("number")?.as_i64()?).ok()?,
                        etag: p.get("etag")?.as_str()?.to_owned(),
                    })
                })
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();

    let recorded = row.get::<i32, _>("part_count") as usize;
    if parts.len() != recorded {
        // The two are written together, so a disagreement means a hand-edited row or a partial
        // write. Completing from it would omit or repeat a part, which S3 accepts and which
        // produces a corrupt object.
        return Err(Error::Inconsistent(format!(
            "upload session {} records {recorded} parts but carries {} — refusing to resume \
             from inconsistent state",
            row.get::<String, _>("upload_id"),
            parts.len()
        )));
    }

    Ok(ResumableSession {
        id: row.get("upload_id"),
        tenant: row.get("tenant_id"),
        declared_length: row
            .get::<Option<i64>, _>("declared_length")
            .map(|v| v as u64),
        offset: row.get::<i64, _>("offset_bytes") as u64,
        s3_upload_id: row.get("backend_upload_id"),
        parts,
        tail_len: row.get::<i64, _>("tail_bytes") as u64,
        status,
    })
}

fn status_str(status: SessionStatus) -> &'static str {
    match status {
        SessionStatus::Active => "active",
        SessionStatus::Completed => "completed",
        SessionStatus::Terminated => "terminated",
    }
}

/// Re-exported so a caller does not need `dam_store` in scope just to read a session's key.
pub use dam_store::resumable::ResumableSession as Session;
