[package]
name = "dam-mcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dam-core = { path = "../dam-core" }
dam-db = { path = "../dam-db" }
dam-search = { path = "../dam-search" }
thiserror = { workspace = true }
rmcp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"

[lints.clippy]
all = { level = "deny", priority = -1 }
todo = "warn"
dbg_macro = "deny"
unwrap_used = "deny"
expect_used = "warn"
