//! Emits the built-in transform names, for connectors that have to name one.
//!
//! A transform is a *name*, not a description. `delivery::op_hash_for` resolves it against the built-in
//! profiles and then the tenant's conversions, and anything else is refused as not deliverable — because
//! approximating a typo'd profile would silently hand back a different size than the caller integrated
//! against.
//!
//! That is the right behaviour and it makes the names an interface. A connector cannot synthesise
//! `w=320,h=320,fit=inside` and expect bytes; it has to say `thumb-256`. So the names have to reach the
//! connector, and a rename here has to break the connector's tests rather than its users' pages.
//!
//! Found by writing the Drupal media source against an invented parameter string, which would have produced
//! a thumbnail URL refused on every request.
//!
//! Regenerate with:
//!
//! ```text
//! cargo run -p dam-media --example transform_names > integrations/drupal/tests/fixtures/transform_names.json
//! ```

use dam_media::profiles;

fn main() {
    // Deliberately not serde: six strings, and the example should not make the crate's dependency graph an
    // argument.
    println!("{{");
    println!(
        "  \"comment\": \"Generated by `cargo run -p dam-media --example transform_names`. Do not edit by hand.\","
    );
    println!("  \"original\": \"{}\",", profiles::ORIGINAL);
    println!("  \"profiles\": [");
    let last = profiles::ALL.len() - 1;
    for (index, profile) in profiles::ALL.iter().enumerate() {
        println!("    {{");
        println!("      \"name\": \"{}\",", profile.name);
        println!("      \"role\": \"{}\",", profile.role);
        println!("      \"width\": {},", profile.rendition.width);
        println!("      \"height\": {}", profile.rendition.height);
        println!("    }}{}", if index == last { "" } else { "," });
    }
    println!("  ]");
    println!("}}");
}
