-- Content provenance and AI disclosure. Closes GAPS.md G1 and G2.
--
-- Two obligations, one mechanism:
--
--   G1  C2PA manifests must survive derivative generation. libvips, ffmpeg, and
--       pdfium all strip embedded metadata by default, so the pipeline as
--       originally designed silently destroyed provenance that cameras, Adobe
--       Creative Cloud, OpenAI, and Google now attach at capture or generation.
--       A DAM is the system of record; it is the worst place in the chain to break
--       it, and serving credential-stripped renditions actively downgrades the
--       customer's content.
--
--   G2  EU AI Act Article 50 has been applicable since 2 August 2026. Providers of
--       systems generating synthetic image/audio/video/text must mark outputs in a
--       MACHINE-READABLE format, and deepfake disclosure applies even without
--       intent to deceive. Penalties reach EUR 15M or 3% of worldwide turnover.
--
-- The `c2pa.ai-disclosure` assertion carries G2's marking inside G1's manifest,
-- so these are one implementation rather than two. That is why the tables live
-- together.


-- ─── manifests ──────────────────────────────────────────────────────────────
-- Manifests are stored as separate objects rather than left as byte ranges inside
-- the asset. Three reasons: the inbound manifest must survive even if the master
-- is later tiered to Deep Archive (a credential is metadata, and metadata stays
-- hot per ARCHITECTURE §2); validation results need somewhere to live; and damrs
-- signs its own manifests for derivatives, which means one asset has many.
--
-- `validation_state` distinguishes three genuinely different situations that a
-- boolean would flatten: an asset that never had credentials, one whose
-- credentials verify, and one whose credentials FAIL to verify. The third is a
-- red flag — possible tampering — and must never be displayed the same way as
-- the first.

CREATE TABLE provenance_manifests (
    id                  uuid PRIMARY KEY,
    asset_id            uuid REFERENCES assets (id) ON DELETE CASCADE,
    derivative_id       uuid REFERENCES derivatives (id) ON DELETE CASCADE,

    -- 'inbound'      as received; never modified, the customer's evidence
    -- 'damrs_signed' generated by us for a derivative, chaining to the inbound one
    role                text NOT NULL CHECK (role IN ('inbound', 'damrs_signed')),
    format              text NOT NULL DEFAULT 'c2pa' CHECK (format IN ('c2pa')),
    spec_version        text,

    object_key          text NOT NULL,       -- the detached manifest blob
    bytes               bigint NOT NULL,
    -- Links a derivative's manifest back to the master's, so the full chain can be
    -- reconstructed without parsing every blob.
    parent_manifest_id  uuid REFERENCES provenance_manifests (id) ON DELETE SET NULL,

    validation_state    text NOT NULL DEFAULT 'unverified'
                            CHECK (validation_state IN ('unverified', 'valid',
                                                        'invalid', 'untrusted',
                                                        'absent')),
    validation_detail   jsonb NOT NULL DEFAULT '{}'::jsonb,
    -- Who signed it. `signer_trusted` is against the C2PA known-certificate list;
    -- a valid signature from an unrecognised signer is 'untrusted', not 'invalid'.
    signer_cn           text,
    signer_chain        jsonb NOT NULL DEFAULT '[]'::jsonb,
    signer_trusted      boolean,
    claim_generator     text,                -- e.g. "Adobe Photoshop 26.1"

    captured_at         timestamptz,         -- from the manifest, not our clock
    verified_at         timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT provenance_owner CHECK (
        (asset_id IS NOT NULL AND derivative_id IS NULL)
        OR (asset_id IS NULL AND derivative_id IS NOT NULL))
);

CREATE INDEX provenance_manifests_asset_idx ON provenance_manifests (asset_id)
    WHERE asset_id IS NOT NULL;
CREATE INDEX provenance_manifests_derivative_idx ON provenance_manifests (derivative_id)
    WHERE derivative_id IS NOT NULL;
CREATE INDEX provenance_manifests_chain_idx ON provenance_manifests (parent_manifest_id);
-- Surfacing failed validation is a product feature, not just an ops concern.
CREATE INDEX provenance_manifests_suspect_idx ON provenance_manifests (validation_state)
    WHERE validation_state IN ('invalid', 'untrusted');
CREATE UNIQUE INDEX provenance_manifests_inbound_idx ON provenance_manifests (asset_id)
    WHERE role = 'inbound' AND asset_id IS NOT NULL;


-- ─── actions ────────────────────────────────────────────────────────────────
-- The chain damrs appends. Every derivative operation is an action: resized,
-- transcoded, cropped, converted. Recording them relationally as well as inside
-- the signed manifest means "what did damrs do to this file" is a query, and it
-- means a manifest can be regenerated from scratch if a signing cert is rotated
-- or a manifest blob is lost.

CREATE TABLE provenance_actions (
    id                  uuid PRIMARY KEY,
    manifest_id         uuid NOT NULL REFERENCES provenance_manifests (id) ON DELETE CASCADE,
    seq                 int NOT NULL,
    -- C2PA action vocabulary where one exists, damrs.* where it does not.
    action              text NOT NULL,       -- c2pa.resized | c2pa.transcoded |
                                             -- c2pa.cropped | c2pa.converted |
                                             -- damrs.enriched | damrs.watermarked
    software_agent      text,
    model_id            uuid REFERENCES ai_models (id) ON DELETE SET NULL,
    parameters          jsonb NOT NULL DEFAULT '{}'::jsonb,
    performed_at        timestamptz NOT NULL DEFAULT now(),

    UNIQUE (manifest_id, seq)
);

CREATE INDEX provenance_actions_manifest_idx ON provenance_actions (manifest_id, seq);


-- ─── AI disclosure (Article 50) ─────────────────────────────────────────────
-- One row per disclosable AI contribution. Per-field rather than per-asset,
-- because the common case is an authentic photograph with an AI-written
-- description — the image needs no disclosure, the description does, and marking
-- the whole asset "AI generated" would be both wrong and commercially damaging.
--
-- `disclosure_kind` is graded rather than boolean because Article 50 draws the
-- line at synthetic or manipulated content, not at any AI involvement. An
-- AI-upscaled photo is in scope; AI-suggested keywords on an untouched photo are
-- not synthetic content, though they are still worth recording for audit.
--
-- `human_oversight` maps to the c2pa.ai-disclosure assertion's oversight field,
-- which captures more than a binary label — model provenance, domain, and degree
-- of human involvement.

CREATE TABLE ai_disclosures (
    id                  uuid PRIMARY KEY,
    asset_id            uuid NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    -- NULL = the asset's own pixels/audio. Otherwise the metadata field affected.
    field_key           text,

    disclosure_kind     text NOT NULL CHECK (disclosure_kind IN (
                            'fully_generated',        -- synthetic; always in scope
                            'substantially_modified', -- inpaint, upscale, bg replace
                            'minor_edit',             -- denoise, auto-levels
                            'metadata_only')),        -- tags/description only
    -- Deepfake disclosure applies even without intent to deceive, so this is a
    -- separate flag rather than an inference from disclosure_kind.
    depicts_real_person boolean NOT NULL DEFAULT false,

    model_id            uuid REFERENCES ai_models (id) ON DELETE SET NULL,
    model_name          text,                -- denormalised: survives model deletion
    prompt_digest       text,                -- hash, not the prompt: may be sensitive
    human_oversight     text NOT NULL DEFAULT 'none'
                            CHECK (human_oversight IN ('none', 'reviewed',
                                                       'edited', 'approved')),

    -- Where the machine-readable mark actually landed. An empty array on a
    -- 'fully_generated' or 'substantially_modified' row is a COMPLIANCE GAP, not
    -- just missing data — see the index below.
    marked_in           text[] NOT NULL DEFAULT '{}',   -- c2pa | xmp | iptc | http_header
    human_visible       boolean NOT NULL DEFAULT false,
    -- Which regimes this row was assessed against; obligations differ by market.
    jurisdictions       text[] NOT NULL DEFAULT '{EU}',

    disclosed_at        timestamptz NOT NULL DEFAULT now(),
    reviewed_by         uuid,
    reviewed_at         timestamptz
);

CREATE INDEX ai_disclosures_asset_idx ON ai_disclosures (asset_id);
CREATE INDEX ai_disclosures_kind_idx ON ai_disclosures (disclosure_kind);

-- The compliance alarm. Any synthetic or substantially-modified content with no
-- machine-readable marking is an Article 50 exposure. This index is what a
-- monitor queries, and it should always return zero rows.
CREATE INDEX ai_disclosures_unmarked_idx ON ai_disclosures (asset_id)
    WHERE disclosure_kind IN ('fully_generated', 'substantially_modified')
      AND cardinality(marked_in) = 0;

-- Deepfakes: content depicting a real person, generated or substantially altered,
-- carries the strictest obligation and its own review queue.
CREATE INDEX ai_disclosures_deepfake_idx ON ai_disclosures (asset_id)
    WHERE depicts_real_person
      AND disclosure_kind IN ('fully_generated', 'substantially_modified');


-- ─── denormalised state on assets ───────────────────────────────────────────
-- Delivery needs to know, per request and without a join, whether this asset
-- requires a visible AI disclosure and whether its credentials are intact.

ALTER TABLE assets
    ADD COLUMN provenance_state text NOT NULL DEFAULT 'none'
        CHECK (provenance_state IN ('none', 'valid', 'invalid', 'untrusted')),
    ADD COLUMN ai_disclosure_state text NOT NULL DEFAULT 'none'
        CHECK (ai_disclosure_state IN ('none', 'metadata_only', 'modified',
                                       'generated', 'deepfake')),
    -- Set when the ingest pipeline detected an inbound manifest. If this is true
    -- and a derivative's manifest is missing, the pipeline dropped a credential
    -- and that is a bug to alert on, not a cosmetic gap.
    ADD COLUMN had_inbound_manifest boolean NOT NULL DEFAULT false;

CREATE INDEX assets_provenance_idx ON assets (provenance_state)
    WHERE provenance_state IN ('invalid', 'untrusted');
CREATE INDEX assets_ai_disclosure_idx ON assets (ai_disclosure_state)
    WHERE ai_disclosure_state <> 'none';


-- ─── derivative credential coverage ─────────────────────────────────────────
-- Detects the G1 regression directly: a derivative of an asset that HAD inbound
-- credentials, where we produced no signed manifest, means the pipeline stripped
-- provenance. Kept as a view because it is a cross-table invariant rather than
-- state, and because it should be wired to an alert rather than a dashboard
-- nobody opens.

CREATE VIEW provenance_gaps AS
SELECT d.id            AS derivative_id,
       d.asset_id,
       d.role,
       d.profile,
       a.had_inbound_manifest,
       d.created_at
FROM derivatives d
JOIN assets a ON a.id = d.asset_id
WHERE a.had_inbound_manifest
  AND d.role IN ('proxy', 'preview', 'rendition')   -- served externally
  AND NOT EXISTS (
      SELECT 1 FROM provenance_manifests pm
      WHERE pm.derivative_id = d.id AND pm.role = 'damrs_signed');
