//! Audio and video probing via ffprobe (finishes 1.7's probe side).
//!
//! Fills `assets.duration_ms` and, for video, the dimensions the grid lays out from. Video *derivatives*
//! are M3.5; this is the metadata half, which ingest needs immediately — an audio file with no duration
//! cannot be shown in a list, let alone played.
//!
//! Fixtures are generated by ffmpeg itself (`sine`, `testsrc`), so the suite carries no binary blobs and
//! every expected value is derivable from the command that produced it.

#![allow(clippy::expect_used, clippy::unwrap_used, clippy::panic)]

use dam_media::avprobe::{self, AvToolchain};
use std::path::{Path, PathBuf};

fn tools() -> AvToolchain {
    AvToolchain::discover().unwrap_or_else(|e| {
        panic!("these tests need ffprobe on PATH; run `mise run check` or `mise exec -- cargo test`: {e}")
    })
}

/// Generates a fixture with ffmpeg and returns its path.
async fn generate(tools: &AvToolchain, dir: &Path, name: &str, args: &[&str]) -> PathBuf {
    let out = dir.join(name);
    let mut full: Vec<String> = vec!["-y".to_owned()];
    full.extend(args.iter().map(|a| (*a).to_owned()));
    full.push(out.to_string_lossy().to_string());
    let borrowed: Vec<&str> = full.iter().map(String::as_str).collect();
    avprobe::run_ffmpeg(tools, &borrowed)
        .await
        .unwrap_or_else(|e| panic!("generating {name}: {e}"));
    out
}

#[tokio::test]
async fn an_audio_file_reports_its_duration_channels_and_sample_rate() {
    let tools = tools();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = generate(
        &tools,
        dir.path(),
        "tone.wav",
        &["-f", "lavfi", "-i", "sine=frequency=440:duration=2"],
    )
    .await;

    let probed = avprobe::probe(&tools, &path).await.expect("probe");
    assert_eq!(probed.duration_ms, Some(2000));
    assert_eq!(probed.channels, Some(1));
    assert_eq!(probed.sample_rate, Some(44_100));
    assert_eq!(probed.audio_codec.as_deref(), Some("pcm_s16le"));
    assert!(probed.is_timed, "audio is time-based media");
    assert_eq!(probed.width, None, "audio has no dimensions");
}

#[tokio::test]
async fn a_fractional_duration_is_not_truncated_to_whole_seconds() {
    // ffprobe reports "1.500000" as a string. Parsing it as an integer number of seconds — or truncating
    // — loses half a second on every clip, which is the difference between a correct HLS manifest and a
    // player that stalls at the end.
    let tools = tools();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = generate(
        &tools,
        dir.path(),
        "short.wav",
        &["-f", "lavfi", "-i", "sine=frequency=440:duration=1.5"],
    )
    .await;

    let probed = avprobe::probe(&tools, &path).await.expect("probe");
    assert_eq!(probed.duration_ms, Some(1500));
}

#[tokio::test]
async fn a_video_reports_its_dimensions_frame_rate_and_codec() {
    let tools = tools();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = generate(
        &tools,
        dir.path(),
        "clip.mp4",
        &[
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=1:size=64x48:rate=10",
            "-pix_fmt",
            "yuv420p",
        ],
    )
    .await;

    let probed = avprobe::probe(&tools, &path).await.expect("probe");
    assert_eq!(probed.duration_ms, Some(1000));
    assert_eq!((probed.width, probed.height), (Some(64), Some(48)));
    assert_eq!(probed.video_codec.as_deref(), Some("h264"));
    assert_eq!(
        probed.frame_rate,
        Some(10.0),
        "10/1 must parse as a rational"
    );
    assert!(probed.is_timed);
}

#[tokio::test]
async fn a_still_image_is_not_reported_as_a_video() {
    // The trap. ffprobe describes a PNG as a **video** stream — codec_type is literally "video" — with
    // format_name `png_pipe` and no duration at all. Treating "has a video stream" as "is a video" would
    // put every photograph in the video pipeline, and `is_timed` is the discriminator that stops it.
    let tools = tools();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = generate(
        &tools,
        dir.path(),
        "still.png",
        &[
            "-f",
            "lavfi",
            "-i",
            "color=c=red:size=32x32:duration=0.04",
            "-frames:v",
            "1",
        ],
    )
    .await;

    let probed = avprobe::probe(&tools, &path).await.expect("probe");
    assert!(
        !probed.is_timed,
        "a PNG is not time-based media however ffprobe labels its stream"
    );
    assert_eq!(
        probed.duration_ms, None,
        "and it must not be given a duration"
    );
    // The dimensions are still useful, and agree with what the image path would report.
    assert_eq!((probed.width, probed.height), (Some(32), Some(32)));
}

#[tokio::test]
async fn a_file_with_both_streams_reports_both_codecs() {
    let tools = tools();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = generate(
        &tools,
        dir.path(),
        "av.mp4",
        &[
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=1:size=32x32:rate=10",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=1",
            "-pix_fmt",
            "yuv420p",
            "-shortest",
        ],
    )
    .await;

    let probed = avprobe::probe(&tools, &path).await.expect("probe");
    assert!(probed.video_codec.is_some(), "expected a video codec");
    assert!(probed.audio_codec.is_some(), "expected an audio codec");
    assert!(probed.is_timed);
}

#[tokio::test]
async fn a_non_media_file_is_an_error_carrying_ffprobes_diagnosis() {
    let tools = tools();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("notes.txt");
    std::fs::write(&path, b"this is not media").expect("write");

    let err = avprobe::probe(&tools, &path)
        .await
        .expect_err("must be refused");
    assert!(
        format!("{err}").len() > 20,
        "the error must carry something actionable: {err}"
    );
}

#[tokio::test]
async fn probing_is_bounded_by_the_sandbox() {
    // ffmpeg's demuxers face the same hostile input as vips's loaders, and have their own CVE history.
    let tools = tools();
    let dir = tempfile::tempdir().expect("tempdir");
    let path = generate(
        &tools,
        dir.path(),
        "bounded.wav",
        &["-f", "lavfi", "-i", "sine=frequency=440:duration=1"],
    )
    .await;

    let outcome = avprobe::probe_with_limits(
        &tools,
        &path,
        dam_media::sandbox::Limits {
            wall_clock: std::time::Duration::from_millis(1),
            ..Default::default()
        },
    )
    .await;
    assert!(outcome.is_err(), "a 1ms wall clock must stop the probe");
}
