//! Emits webhook signature vectors, for a receiver written in another language.
//!
//! Every connector has to verify these, and a receiver that verifies them *wrongly in the accepting
//! direction* is an endpoint anybody can post to. That is a different severity from the delivery-token
//! vectors: there, a mistake means images stop rendering, and here it means somebody else's payload gets
//! treated as ours.
//!
//! So the vectors deliberately include the forgeries a plausible implementation accepts:
//!
//! - the right digest over the body alone, with no timestamp — which passes if the receiver forgot that the
//!   signed string is `timestamp.body`, and makes every signature a permanent replay token,
//! - a valid signature presented with a different timestamp,
//! - the correct hex with the `v1=` prefix missing, and with it uppercased,
//! - a body differing by one byte.
//!
//! A receiver that accepts any of those has a hole, and a suite built only from the happy path would not
//! say so.
//!
//! Regenerate with:
//!
//! ```text
//! cargo run -p dam-connect --example webhook_vectors > integrations/drupal/tests/fixtures/webhook_vectors.json
//! ```

use dam_connect::webhooks::sign;
use dam_core::Secret;

const SECRET: &str = "webhook-secret-do-not-use-in-production";

fn main() {
    let secret = Secret::new(SECRET.to_owned());
    let timestamp: i64 = 1_800_000_000;
    let body = r#"{"event":"asset.metadata_updated","asset_id":"66666666-7777-8888-9999-aaaaaaaaaaaa","occurred_at":"2027-01-15T09:26:40Z","detail":{"fields":["title","alt_text"]}}"#;

    let good = sign(&secret, timestamp, body.as_bytes());

    // The forgery a receiver that signs the body alone would accept. Built here rather than described, so
    // the fixture carries the actual bytes a wrong implementation produces.
    let body_only = {
        use hmac::{Hmac, Mac};
        use sha2::Sha256;
        #[allow(clippy::expect_used)]
        let mut mac =
            <Hmac<Sha256>>::new_from_slice(SECRET.as_bytes()).expect("hmac takes any key length");
        mac.update(body.as_bytes());
        let digest = mac.finalize().into_bytes();
        let hex: String = digest.iter().map(|b| format!("{b:02x}")).collect();
        format!("v1={hex}")
    };

    let other_body = r#"{"event":"asset.deleted","asset_id":"66666666-7777-8888-9999-aaaaaaaaaaaa","occurred_at":"2027-01-15T09:26:40Z","detail":{}}"#;

    println!("{{");
    println!(
        "  \"comment\": \"Generated by `cargo run -p dam-connect --example webhook_vectors`. Do not edit by hand.\","
    );
    println!("  \"secret\": {},", json(SECRET));
    println!("  \"timestamp\": {timestamp},");
    println!("  \"body\": {},", json(body));
    println!("  \"valid_signature\": {},", json(&good));
    println!("  \"must_reject\": [");
    let rejects: Vec<(&str, String, i64, &str)> = vec![
        (
            "signed the body without the timestamp",
            body_only,
            timestamp,
            body,
        ),
        (
            "valid signature, different timestamp",
            good.clone(),
            timestamp + 1,
            body,
        ),
        (
            "valid signature, one byte of body changed",
            good.clone(),
            timestamp,
            other_body,
        ),
        (
            "correct digest, no version prefix",
            good.trim_start_matches("v1=").to_owned(),
            timestamp,
            body,
        ),
        (
            "correct digest, uppercased hex",
            format!("v1={}", good.trim_start_matches("v1=").to_uppercase()),
            timestamp,
            body,
        ),
        ("empty signature", String::new(), timestamp, body),
        (
            "a different scheme version",
            good.replacen("v1=", "v2=", 1),
            timestamp,
            body,
        ),
    ];
    let last = rejects.len() - 1;
    for (index, (why, signature, ts, b)) in rejects.iter().enumerate() {
        println!("    {{");
        println!("      \"why\": {},", json(why));
        println!("      \"signature\": {},", json(signature));
        println!("      \"timestamp\": {ts},");
        println!("      \"body\": {}", json(b));
        println!("    }}{}", if index == last { "" } else { "," });
    }
    println!("  ]");
    println!("}}");
}

fn json(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
